#!/usr/bin/env python3
"""
Render analyzer output as a daily Markdown digest.

The digest lives at `docs/mothership/llm-monitor/digests/YYYY-MM-DD.md`
(committed by the workflow so the operator can read it from any
surface — web, mobile, terminal). It is *not* a pinned issue; the
existing backlog-digest covers that surface and we don't want to
crowd it.

Layout (top-to-bottom):

  1. Date + total counts (by kind / subject / severity).
  2. **High-signal items** — every classified record with severity ≥ 4,
     grouped by subject. This is what feedback.py also acts on.
  3. **Best practices & features** — severity 3, kind ≠ bug.
  4. **Other coverage** — severity ≤ 2 condensed to one line each.
  5. Footer: model used, generated_at timestamp.

Usage:
    python3 scripts/llm-monitor/digest.py \
        --analyzer-output state/analyzer-2026-04-30.json \
        --out docs/mothership/llm-monitor/digests/2026-04-30.md
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

KIND_LABELS = {
    "bug": "Bug",
    "feature": "Feature",
    "best_practice": "Best practice",
    "comparison": "Comparison",
    "news": "News",
    "noise": "Noise",
}

SUBJECT_ORDER = [
    "claude-opus-4-7", "claude-sonnet-4-6", "claude-haiku-4-5",
    "claude-code", "anthropic-sdk", "mcp",
    "openai-gpt-5.5", "openai-codex",
    "gemini-2.5-pro", "gemini-2.5-flash",
    "general",
]


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _src_label(src: str) -> str:
    return {"hackernews": "HN", "rss": "RSS", "reddit": "Reddit",
            "github": "GitHub"}.get(src, src)


def render(analyzer_output: dict, today: str | None = None) -> str:
    today = today or _today()
    summary = analyzer_output.get("summary", {})
    records = analyzer_output.get("records", [])
    originals = analyzer_output.get("originals_by_id", {})

    lines: list[str] = []
    lines.append(f"# LLM monitor digest — {today}")
    lines.append("")
    lines.append("> _Auto-generated by `scripts/llm-monitor/digest.py`. "
                 "Don't hand-edit; edit upstream config in `sources.json`._")
    lines.append("")

    # --- Counts table ---
    total = summary.get("total", 0)
    lines.append(f"**{total} records analyzed** "
                 f"(model: `{summary.get('model', 'unknown')}`).")
    lines.append("")
    by_kind = summary.get("by_kind", {})
    if by_kind:
        lines.append("| Kind | Count |")
        lines.append("|---|---:|")
        for k in ("bug", "feature", "best_practice", "comparison", "news", "noise"):
            if k in by_kind:
                lines.append(f"| {KIND_LABELS[k]} | {by_kind[k]} |")
        lines.append("")

    # --- High-signal section ---
    high = [r for r in records if r.get("severity", 0) >= 4
            and r.get("kind") != "noise"]
    if high:
        lines.append("## High-signal items")
        lines.append("")
        by_subject: dict[str, list] = defaultdict(list)
        for r in high:
            by_subject[r.get("subject", "general")].append(r)
        for subj in SUBJECT_ORDER:
            items = by_subject.get(subj, [])
            if not items:
                continue
            lines.append(f"### {subj}")
            lines.append("")
            for r in items:
                orig = originals.get(r["id"], {})
                src = _src_label(orig.get("source", ""))
                url = orig.get("url", "")
                title = orig.get("title", r.get("summary", ""))
                sev = r.get("severity", 0)
                lines.append(
                    f"- **[sev {sev}] {KIND_LABELS.get(r['kind'], r['kind'])}** — "
                    f"{r.get('summary', title)}  \n"
                    f"  Source: [{src}]({url}) · "
                    f"id: `{r['id']}`"
                )
                if r.get("action_hint"):
                    lines.append(f"  > **Action:** {r['action_hint']}")
            lines.append("")

    # --- Best practices & features (sev 3) ---
    mid = [r for r in records if r.get("severity", 0) == 3
           and r.get("kind") in ("best_practice", "feature", "news")]
    if mid:
        lines.append("## Best practices, features & news")
        lines.append("")
        for r in mid:
            orig = originals.get(r["id"], {})
            src = _src_label(orig.get("source", ""))
            url = orig.get("url", "")
            lines.append(
                f"- **{KIND_LABELS.get(r['kind'], r['kind'])} ({r.get('subject', 'general')})** "
                f"— {r.get('summary', '')} "
                f"[{src}]({url})"
            )
        lines.append("")

    # --- Other (sev ≤ 2) condensed ---
    low = [r for r in records if r.get("severity", 0) <= 2
           and r.get("kind") != "noise"]
    if low:
        lines.append("## Other coverage")
        lines.append("")
        lines.append(f"_{len(low)} lower-signal records collapsed for brevity._ "
                     "Full data: `state/raw/`.")
        lines.append("")

    lines.append("---")
    lines.append(f"_Generated {summary.get('generated_at', 'unknown')}_")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--analyzer-output", required=True,
                    help="JSON file written by analyzer.py")
    ap.add_argument("--out", help="Markdown output path (default: stdout)")
    ap.add_argument("--date", help="Override today's date (YYYY-MM-DD)")
    args = ap.parse_args()

    with open(args.analyzer_output) as fh:
        data = json.load(fh)
    md = render(data, today=args.date)

    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(md)
    else:
        import sys
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
