#!/usr/bin/env python3
"""
Newsletter renderers — turn analyzer output into two distinct surfaces:

  * **Operator newsletter** — technical, written for the human running
    this pipeline. Includes severity, action_hints, recommendations,
    impact_targets, and per-stack-component sections. Stored at
    `docs/mothership/llm-monitor/newsletters/operator-YYYY-MM-DD.md`.
  * **Client newsletter** — plain-English, written for prospective
    clients. Excludes anything with empty `client_summary`, drops jargon,
    frames items as "what this means for you". Stored at
    `docs/mothership/llm-monitor/newsletters/client-YYYY-MM-DD.md`.
    Per the user's directive: stored in the repo for now; an emailing
    delivery channel is deferred until v2.

The split is deliberate: the operator surface is dense and engineering-
flavoured; the client surface is intentionally conservative and only
mentions an item when the analyzer has produced a real client_summary.
That keeps marketing copy out of the operator's face and engineering
detail out of the client's face.

CLI:
    python3 scripts/llm-monitor/newsletters.py \
        --analyzer-output state/analyzer-2026-04-30.json \
        --operator-out docs/mothership/llm-monitor/newsletters/operator-2026-04-30.md \
        --client-out   docs/mothership/llm-monitor/newsletters/client-2026-04-30.md
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

KIND_LABEL = {
    "bug": "Bug / regression",
    "feature": "Feature",
    "best_practice": "Best practice",
    "comparison": "Comparison",
    "news": "News",
    "noise": "Noise",
}

IMPACT_LABEL = {
    "site": "Site (Client #1 marketing site)",
    "pipeline": "Pipeline (Lumivara Forge bot framework)",
    "mothership": "Mothership (operator strategy / docs)",
    "storefront": "Storefront (client-facing storefront)",
    "client_repos": "Client repos (delivery work)",
}

IMPACT_ORDER = ["pipeline", "site", "storefront", "mothership", "client_repos"]


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _src_label(src: str) -> str:
    return {"hackernews": "HN", "rss": "RSS", "reddit": "Reddit",
            "github": "GitHub"}.get(src, src)


def render_operator(analyzer_output: dict, today: str | None = None) -> str:
    today = today or _today()
    summary = analyzer_output.get("summary", {})
    records = analyzer_output.get("records", [])
    originals = analyzer_output.get("originals_by_id", {})

    lines: list[str] = []
    lines.append(f"# Operator technical newsletter — {today}")
    lines.append("")
    lines.append(f"> _Auto-generated by `scripts/llm-monitor/newsletters.py`. "
                 f"Source data: `state/analyzer-{today}.json`._")
    lines.append("")
    lines.append("## At a glance")
    lines.append("")
    total = summary.get("total", 0)
    lines.append(f"- Records analyzed: **{total}** (model: "
                 f"`{summary.get('model', 'unknown')}`)")
    by_kind = summary.get("by_kind", {})
    if by_kind:
        kind_str = ", ".join(f"{KIND_LABEL.get(k, k).lower()}: {v}"
                             for k, v in by_kind.items())
        lines.append(f"- By kind: {kind_str}")
    by_impact = summary.get("by_impact", {})
    if by_impact:
        impact_str = ", ".join(f"{k}: {v}" for k, v in by_impact.items())
        lines.append(f"- By impact target: {impact_str}")
    lines.append("")

    # --- Per-impact sections ---
    high = [r for r in records if r.get("severity", 0) >= 4
            and r.get("kind") != "noise"]
    if high:
        lines.append("## What needs your attention this week")
        lines.append("")
        # Group by impact target — the operator wants to scan "what
        # affects the pipeline?" then "what affects the site?" etc.
        by_target: dict[str, list] = defaultdict(list)
        for r in high:
            for tgt in r.get("impact_targets") or ["general"]:
                by_target[tgt].append(r)
        for tgt in IMPACT_ORDER + sorted(set(by_target) - set(IMPACT_ORDER)):
            items = by_target.get(tgt, [])
            if not items:
                continue
            lines.append(f"### Impact: {IMPACT_LABEL.get(tgt, tgt)}")
            lines.append("")
            for r in items:
                orig = originals.get(r["id"], {})
                src = _src_label(orig.get("source", ""))
                url = orig.get("url", "")
                sev = r.get("severity", 0)
                lines.append(
                    f"- **[sev {sev}] {KIND_LABEL.get(r['kind'], r['kind'])}** "
                    f"on `{r.get('subject', '?')}` — {r.get('summary', '')}  "
                )
                lines.append(f"  Source: [{src}]({url}) · "
                             f"id: `{r['id']}`")
                if r.get("action_hint"):
                    lines.append(f"  - **TODO (action):** {r['action_hint']}")
                if r.get("recommendation"):
                    lines.append(f"  - **TODO (system):** {r['recommendation']}")
            lines.append("")

    # --- Recommendations callout ---
    recs = summary.get("recommendations", [])
    if recs:
        lines.append("## Self-automation system suggestions")
        lines.append("")
        lines.append(f"_{len(recs)} record(s) suggested an enhancement to "
                     f"the bot fleet itself. These are appended to "
                     f"[`RECOMMENDATIONS.md`](../RECOMMENDATIONS.md) for "
                     f"review at the next architecture pass._")
        lines.append("")
        for r in recs[:20]:
            lines.append(f"- `{r.get('subject', '?')}` → "
                         f"{r.get('recommendation', '')}")
        lines.append("")

    # --- Best practices and news ---
    mid = [r for r in records if r.get("severity", 0) == 3
           and r.get("kind") in ("best_practice", "feature", "news")]
    if mid:
        lines.append("## Best practices, features, and news (informational)")
        lines.append("")
        for r in mid:
            orig = originals.get(r["id"], {})
            src = _src_label(orig.get("source", ""))
            url = orig.get("url", "")
            lines.append(f"- **{KIND_LABEL.get(r['kind'], r['kind'])}** "
                         f"({r.get('subject', '?')}): {r.get('summary', '')} "
                         f"[{src}]({url})")
        lines.append("")

    lines.append("---")
    lines.append(f"_Generated {summary.get('generated_at', 'unknown')}_")
    lines.append("")
    return "\n".join(lines)


def render_client(analyzer_output: dict, today: str | None = None) -> str:
    today = today or _today()
    summary = analyzer_output.get("summary", {})
    client_items = summary.get("client_items", [])

    lines: list[str] = []
    lines.append(f"# What's new in the AI tools we use — {today}")
    lines.append("")
    lines.append(
        "> _A short, plain-English digest of changes in the AI and "
        "automation tools that power the work we deliver. Auto-generated; "
        "stored in the repo for now and emailed to subscribers when the "
        "delivery channel is wired up._"
    )
    lines.append("")

    if not client_items:
        lines.append("Nothing client-relevant this cycle. We're still "
                     "watching closely — the technical pipeline picked up "
                     f"{summary.get('total', 0)} engineering-only items "
                     "in the same window.")
        lines.append("")
        return "\n".join(lines)

    # Group by impact in client-friendly way: what affects "delivery
    # speed" vs "AI capability" vs "reliability" — but we don't have
    # that taxonomy yet, so for v1 just list them with a category
    # derived from kind.
    lines.append("## This week's highlights")
    lines.append("")
    for item in client_items:
        category = {
            "bug": "🛠 Issue we're tracking",
            "feature": "✨ New capability",
            "best_practice": "📘 Improved approach",
            "comparison": "📊 Tooling comparison",
            "news": "📣 Announcement",
        }.get(item.get("kind", "news"), "📣 Update")
        lines.append(f"- **{category}** — {item.get('client_summary', '')}")
    lines.append("")

    lines.append("## Why this matters to you")
    lines.append("")
    lines.append(
        "The tools above are the same ones we use day-to-day to build, "
        "operate, and improve the work we deliver. When they get faster, "
        "smarter, or more reliable, those gains flow through to your "
        "engagements directly. When they regress, we catch it early "
        "(usually before you notice) because the same pipeline that "
        "writes this digest also files internal tickets when something "
        "breaks."
    )
    lines.append("")
    lines.append(
        "If you'd like to see a deeper dive on any of these items, reply "
        "to this email — we keep client-specific impact notes in our "
        "engagement evidence log."
    )
    lines.append("")
    lines.append("---")
    lines.append(f"_Generated {summary.get('generated_at', 'unknown')}. "
                 f"Auto-curated by Lumivara Forge._")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--analyzer-output", required=True)
    ap.add_argument("--operator-out", required=True)
    ap.add_argument("--client-out", required=True)
    ap.add_argument("--date")
    args = ap.parse_args()

    with open(args.analyzer_output) as fh:
        data = json.load(fh)

    op_md = render_operator(data, today=args.date)
    cl_md = render_client(data, today=args.date)

    Path(args.operator_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.operator_out).write_text(op_md)
    Path(args.client_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.client_out).write_text(cl_md)
    print(f"[newsletters] wrote {args.operator_out}, {args.client_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
